# Site settings
title: kaikoroku
email: fahmi.ardhianto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  fahmiardhianto's personal blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fahmiardhianto.github.io" # the base hostname & protocol for your site
twitter_username: fahmiardhianto
github_username:  fahmiardhianto

# Build settings
markdown: kramdown
